package com.nazir.urlshortener.unit.service;

import com.nazir.urlshortener.config.AppProperties;
import com.nazir.urlshortener.config.AppProperties.CorsProperties;
import com.nazir.urlshortener.config.AppProperties.SlugProperties;
import com.nazir.urlshortener.domain.ShortUrl;
import com.nazir.urlshortener.dto.mapper.ShortUrlMapper;
import com.nazir.urlshortener.dto.request.CreateShortUrlRequest;
import com.nazir.urlshortener.dto.request.UpdateShortUrlRequest;
import com.nazir.urlshortener.dto.response.ShortUrlResponse;
import com.nazir.urlshortener.exception.ShortUrlNotFoundException;
import com.nazir.urlshortener.repository.ShortUrlRepository;
import com.nazir.urlshortener.service.ShortUrlService;
import com.nazir.urlshortener.service.SlugGeneratorService;
import com.nazir.urlshortener.service.UrlValidationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("ShortUrlService")
class ShortUrlServiceTest {

    @Mock
    private ShortUrlRepository shortUrlRepository;
    @Mock
    private SlugGeneratorService slugGeneratorService;
    @Mock
    private UrlValidationService urlValidationService;
    @Mock
    private PasswordEncoder passwordEncoder;

    private ShortUrlService shortUrlService;
    private ShortUrlMapper shortUrlMapper;

    @BeforeEach
    void setUp() {
        AppProperties props = new AppProperties(
            "http://localhost:8080",
            new SlugProperties(7, 3, 20),
            new CorsProperties(List.of("http://localhost:3000"))
        );
        shortUrlMapper = new ShortUrlMapper(props);
        shortUrlService = new ShortUrlService(
            shortUrlRepository, slugGeneratorService,
            urlValidationService, shortUrlMapper, passwordEncoder
        );
    }

    @Nested
    @DisplayName("create()")
    class Create {

        @Test
        void shouldCreateWithAutoGeneratedSlug() {
            // Arrange
            var request = new CreateShortUrlRequest(
                "https://example.com", null, null, null, null, null);

            when(urlValidationService.validateAndNormalize("https://example.com"))
                .thenReturn("https://example.com");
            when(slugGeneratorService.generateUniqueSlug()).thenReturn("abc1234");
            when(shortUrlRepository.save(any(ShortUrl.class)))
                .thenAnswer(inv -> {
                    ShortUrl entity = inv.getArgument(0);
                    entity.setId(UUID.randomUUID());
                    entity.setCreatedAt(LocalDateTime.now());
                    entity.setUpdatedAt(LocalDateTime.now());
                    return entity;
                });

            // Act
            ShortUrlResponse result = shortUrlService.create(request);

            // Assert
            assertThat(result.slug()).isEqualTo("abc1234");
            assertThat(result.originalUrl()).isEqualTo("https://example.com");
            assertThat(result.shortUrl()).isEqualTo("http://localhost:8080/abc1234");
            assertThat(result.isPasswordProtected()).isFalse();
            assertThat(result.clickCount()).isZero();
        }

        @Test
        void shouldCreateWithCustomSlug() {
            var request = new CreateShortUrlRequest(
                "https://example.com", "my-link", null, null, null, null);

            when(urlValidationService.validateAndNormalize(any())).thenReturn("https://example.com");
            when(slugGeneratorService.validateCustomSlug("my-link")).thenReturn("my-link");
            when(shortUrlRepository.save(any(ShortUrl.class)))
                .thenAnswer(inv -> {
                    ShortUrl entity = inv.getArgument(0);
                    entity.setId(UUID.randomUUID());
                    entity.setCreatedAt(LocalDateTime.now());
                    entity.setUpdatedAt(LocalDateTime.now());
                    return entity;
                });

            ShortUrlResponse result = shortUrlService.create(request);

            assertThat(result.slug()).isEqualTo("my-link");
            verify(slugGeneratorService).validateCustomSlug("my-link");
            verify(slugGeneratorService, never()).generateUniqueSlug();
        }

        @Test
        void shouldHashPasswordWhenProvided() {
            var request = new CreateShortUrlRequest(
                "https://example.com", null, null, "secret123", null, null);

            when(urlValidationService.validateAndNormalize(any())).thenReturn("https://example.com");
            when(slugGeneratorService.generateUniqueSlug()).thenReturn("xyz7890");
            when(passwordEncoder.encode("secret123")).thenReturn("$2a$10$hashed");
            when(shortUrlRepository.save(any(ShortUrl.class)))
                .thenAnswer(inv -> {
                    ShortUrl entity = inv.getArgument(0);
                    entity.setId(UUID.randomUUID());
                    entity.setCreatedAt(LocalDateTime.now());
                    entity.setUpdatedAt(LocalDateTime.now());
                    return entity;
                });

            ShortUrlResponse result = shortUrlService.create(request);

            ArgumentCaptor<ShortUrl> captor = ArgumentCaptor.forClass(ShortUrl.class);
            verify(shortUrlRepository).save(captor.capture());
            assertThat(captor.getValue().getPasswordHash()).isEqualTo("$2a$10$hashed");
            assertThat(result.isPasswordProtected()).isTrue();
        }
    }

    @Nested
    @DisplayName("getBySlug()")
    class GetBySlug {

        @Test
        void shouldReturnShortUrlWhenFound() {
            ShortUrl entity = ShortUrl.builder()
                .id(UUID.randomUUID())
                .slug("abc123")
                .originalUrl("https://example.com")
                .build();
            entity.setCreatedAt(LocalDateTime.now());
            entity.setUpdatedAt(LocalDateTime.now());

            when(shortUrlRepository.findBySlug("abc123")).thenReturn(Optional.of(entity));

            ShortUrlResponse result = shortUrlService.getBySlug("abc123");

            assertThat(result.slug()).isEqualTo("abc123");
            assertThat(result.originalUrl()).isEqualTo("https://example.com");
        }

        @Test
        void shouldThrowWhenNotFound() {
            when(shortUrlRepository.findBySlug("missing")).thenReturn(Optional.empty());

            assertThatThrownBy(() -> shortUrlService.getBySlug("missing"))
                .isInstanceOf(ShortUrlNotFoundException.class)
                .hasMessageContaining("missing");
        }
    }

    @Nested
    @DisplayName("update()")
    class Update {

        @Test
        void shouldUpdateOnlyNonNullFields() {
            ShortUrl existing = ShortUrl.builder()
                .id(UUID.randomUUID())
                .slug("abc123")
                .originalUrl("https://old.com")
                .active(true).build();
            existing.setCreatedAt(LocalDateTime.now());
            existing.setUpdatedAt(LocalDateTime.now());

            when(shortUrlRepository.findBySlug("abc123")).thenReturn(Optional.of(existing));
            when(urlValidationService.validateAndNormalize("https://new.com"))
                .thenReturn("https://new.com");
            when(shortUrlRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

            var request = new UpdateShortUrlRequest("https://new.com", null, null, null);
            ShortUrlResponse result = shortUrlService.update("abc123", request);

            assertThat(result.originalUrl()).isEqualTo("https://new.com");
            assertThat(result.isActive()).isTrue(); // unchanged since request.isActive was null
        }
    }

    @Nested
    @DisplayName("delete()")
    class Delete {

        @Test
        void shouldDeleteExistingUrl() {
            ShortUrl existing = ShortUrl.builder()
                .id(UUID.randomUUID())
                .slug("abc123")
                .originalUrl("https://example.com")
                .build();

            when(shortUrlRepository.findBySlug("abc123")).thenReturn(Optional.of(existing));

            shortUrlService.delete("abc123");

            verify(shortUrlRepository).delete(existing);
        }

        @Test
        void shouldThrowWhenDeletingNonExistent() {
            when(shortUrlRepository.findBySlug("nope")).thenReturn(Optional.empty());

            assertThatThrownBy(() -> shortUrlService.delete("nope"))
                .isInstanceOf(ShortUrlNotFoundException.class);
        }
    }
}
